POST http://localhost:8080/reg?id=123&name=Egor&username=Geednwled&password=sskwdwed&role=admin
Content-Type: application/x-www-form-urlencoded
###
POST http://localhost:8080/approveComment?id=1
Content-Type: application/x-www-form-urlencoded
###
POST http://localhost:8080/approvePost?id=2
Content-Type: application/x-www-form-urlencoded
###
POST http://localhost:8080/authorization?name=Egor&username=Geednwled
Content-Type: application/x-www-form-urlencoded
###
POST http://localhost:8080/createComment?postid=2
Content-Type: application/x-www-form-urlencoded
###
POST http://localhost:8080/reg?name=Egor&username=Geednwled&password=sskwdwed&role=admin
Content-Type: application/x-www-form-urlencoded
###
POST http://localhost:8080/reg?name=Egor&username=Geednwled&password=sskwdwed&role=admin
Content-Type: application/x-www-form-urlencoded
###
POST http://localhost:8080/reg?name=Egor&username=Geednwled&password=sskwdwed&role=admin
Content-Type: application/x-www-form-urlencoded
###